# Generated by Django 6.0.3 on 2026-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tirle', models.CharField(max_length=150, verbose_name='Title')),
            ],
        ),
    ]
