# Generated by Django 6.0.3 on 2026-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150, verbose_name='Heading')),
                ('body', models.TextField(default='Article body', verbose_name='Body')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
