# Generated by Django 6.0.3 on 2026-03-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='autor',
            new_name='author',
        ),
    ]
