# Generated by Django 6.0.3 on 2026-03-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_autor_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='genre',
            new_name='theme',
        ),
    ]
